base_local_planner: base_local_planner/TrajectoryPlannerROS

TrajectoryPlannerROS:
    max_vel_x: 0.3
    min_vel_x: 0.1
    max_vel_theta: 2.0
    min_in_place_vel_theta: 0.8
  
    acc_lim_theta: 3.2
    acc_lim_x: 1.8
    acc_lim_y: 1.8
  
    holonomic_robot: false